name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=2.15.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cloud_firestore: ^5.4.4
  provider: ^6.0.2
  
# dependency_overrides:
#   firebase_core_platform_interface: 4.5.1

# dev_dependencies:
#   flutter_lints: ^1.0.4
#   flutter_test:
#     sdk: flutter
